using Microsoft.EntityFrameworkCore;
using WebApp7BySupriya.Data.Entities;

namespace WebApp7BySupriya.Data
{
    // This file simulates a scaffolded DbContext generated by EF Core database-first.
    public partial class SchoolContext : DbContext
    {
        public SchoolContext(DbContextOptions<SchoolContext> options) : base(options) { }

        public virtual DbSet<Student> Students { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Student>(entity =>
            {
                entity.ToTable("Students");
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Name).IsRequired();
                entity.Property(e => e.Email).IsRequired();
                entity.Property(e => e.Faculty).IsRequired();
                entity.Property(e => e.Gpa).HasColumnType("REAL");
            });
        }
    }
}
